version: '3.9'

services:
  app:
    build:
      context: .      
    container_name: node
    tty: true
    stdin_open: true
    working_dir: /code
    volumes:
      - ./files:/code
    ports:
      - 80:80
      - 3000:3000
